version: "3.9"

services:
  db:
    image: postgres:16
    container_name: lectopolis_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: lectopolisdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: lectopolis_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lectopolis.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "5050:80"
    depends_on:
      - db
